name: Deploy to Supabase

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy Supabase Edge Functions
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        run: |
          # Deploy all functions in the supabase/functions folder (adjust names if needed)
          if [ -d "supabase/functions" ]; then
            for fn in supabase/functions/*; do
              if [ -d "$fn" ]; then
                name=$(basename "$fn")
                echo "Deploying function: $name"
                supabase functions deploy "$name" --project-ref "$SUPABASE_PROJECT_REF" --token "$SUPABASE_ACCESS_TOKEN" || exit 1
              fi
            done
          else
            echo "No supabase/functions directory found, skipping functions deploy"
          fi

      - name: Deploy static hosting (optional)
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        run: |
          # If you have a static site build (for example next export output), update this path
          if [ -d "supabase/hosting" ]; then
            echo "Deploying hosting from supabase/hosting"
            supabase hosting deploy ./supabase/hosting --project-ref "$SUPABASE_PROJECT_REF" --token "$SUPABASE_ACCESS_TOKEN" || echo "hosting deploy failed or not configured"
          else
            echo "No supabase/hosting directory found, skipping hosting deploy"
          fi
