[build]
builder = "nixpacks"

[deploy]
startCommand = "uvicorn simple_app:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
PYTHON_VERSION = "3.11"
ENVIRONMENT = "production"
