project_id = "ofsfbmahiysfhkmazlzg"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[storage]
enabled = true

[auth]
enabled = true
site_url = "https://app.celora.net"
additional_redirect_urls = ["https://celora.net", "https://api.celora.net", "http://localhost:3000"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[functions.celora-hosting]
verify_jwt = false

[functions.celora-api]
verify_jwt = false
